version: '3'

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "9090:8080"     # 웹 UI
      - "50000:50000"   # (선택) 에이전트 JNLP
    volumes:
      - jenkins-home:/var/jenkins_home        # 젠킨스 데이터 영구화
      - /var/run/docker.sock:/var/run/docker.sock  # 호스트 Docker 사용(DooD)
    restart: unless-stopped
    # (리눅스 권한 문제 시)
    # user: "1000:1000"

volumes:
  grafana-storage:
  jenkins-home:
