version: '3'

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"     # 브라우저 접속 포트 변경
      - "50000:50000"   # 에이전트 연결 포트
    volumes:
      - jenkins-home:/var/jenkins_home
    restart: unless-stopped

volumes:
  grafana-storage:
  jenkins-home:
