version: '3'

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock            # 호스트 Docker 데몬
      - /usr/bin/docker:/usr/bin/docker                      # 호스트 docker CLI
      - /usr/local/lib/docker/cli-plugins:/usr/local/lib/docker/cli-plugins   # compose/buildx 플러그인 경로
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins       # (일부 환경용 추가 경로)
    restart: unless-stopped

volumes:
  grafana-storage:
  jenkins-home:
